{application,erank,
             [{description,[]},
              {vsn,"0.0.2"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{erank_app,[]}},
              {env,[]},
              {modules,[erank_api,erank_app,erank_misc,erank_server,erank_sup,
                        erank_util,eredis_api,eredis_keygen]}]}.
